### ISSUE TITLE
Testing suite is missing

### ISSUE THREAD

**Issue by edran** [torrvision/crayon#3]
We should have a testing suite to run on Travis.

## TODO

* [x] Set testing suite for `[py2.7, py3.*]` with `tox`. For Lua we'll have to check what can be done in terms of test discovery.
* [x] Investigate running tensorboard on Travis.
* [x] Write a `travis.yml` file.

**Comment by albanD** [comment]
Travis is built to run for [albanD/crayon](https://github.com/albanD/crayon)'s master branch.
Docker and Pypi builds will run when a new tag is uploaded on the same repo.
